# -*- coding: utf-8 -*-
"""Los nueve instrumentos del libro de evaluacion, extraidos de sus hojas.

GENERADO por generadores/_extraer_bateria.py. No editar a mano.
Fuente: Evaluacion Psicologica - Hogar Terapeutico.xlsx
"""

ESCALAS = {'likert5': ['Muy en desacuerdo',
             'Ligeramente en desacuerdo',
             'Ni de acuerdo, ni en desacuerdo',
             'Ligeramente de acuerdo',
             'Muy de acuerdo'],
 'stai': ['Nada', 'Algo', 'Bastante', 'Mucho'],
 'frec5': ['Casi nunca',
           'Pocas veces',
           'Unas veces sí y otras no',
           'Muchas veces',
           'Casi siempre']}

BATERIA = {'5big': {'rotulo': 'Personalidad (5BIG)',
          'tipo': 'escala',
          'escala': 'likert5',
          'enunciado': 'Las siguientes expresiones le describen a usted con más o menos '
                       'precisión. Marque la opción que considere correcta.',
          'items': ['Es hablador/a',
                    'Tiende a ser criticón/a',
                    'Es minucioso/a en el trabajo',
                    'Tiende a ponerse triste o melancólico/a',
                    'Es original, se le ocurren ideas nuevas',
                    'Es reservado/a',
                    'Es generoso/a y ayuda a los demás',
                    'Puede a veces ser algo descuidado/a',
                    'Es calmado/a, controla bien el estrés',
                    'Tiene intereses muy diversos',
                    'Está lleno/a de energía',
                    'Prefiere trabajos que son rutinarios',
                    'Inicia disputas con los demás',
                    'Es un trabajador/a cumplidor, digno de confianza',
                    'Con frecuencia se pone tenso',
                    'Tiende a ser callado',
                    '17. Valora lo artístico, lo estético',
                    '18. Tiende a ser desorganizado',
                    '19. Es emocionalmente estable, difícil de alterar',
                    '20. Tiene una imaginación activa',
                    '21. Persevera hasta terminar el trabajo',
                    '22. Es a veces maleducado con los demás',
                    '23. Es inventivo',
                    '24. Es generalmente confiado',
                    '25. Tiende a ser flojo, vago',
                    '26. Se preocupa mucho por las cosas',
                    '27. Es a veces tímido, inhibido',
                    '28. Es indulgente, no le cuesta perdonar',
                    '29. Hace las cosas de manera eficiente',
                    '30. Es temperamental, de humor cambiante',
                    '31. Es ingenioso, analítico',
                    '32. Irradia entusiasmo',
                    '33. Es a veces frío y distante',
                    '34. Hace planes y los sigue cuidadosamente',
                    '35. Mantiene la calma en situaciones difíciles',
                    '36. Le gusta reflexionar, jugar con las ideas',
                    '37. Es considerado y amable con casi todo el mundo',
                    '38. Se pone nervioso con facilidad',
                    '39. Es educado en arte, música, o literatura',
                    '40. Es asertivo, no teme expresar lo que quiere',
                    '41. Le gusta cooperar con los demás',
                    '42. Se distrae con facilidad',
                    '43. Es extrovertido, sociable',
                    '44. Tiene pocos intereses artísticos']},
 'af5': {'rotulo': 'Autoconcepto (AF-5)',
         'tipo': 'numero',
         'minimo': 1,
         'maximo': 99,
         'enunciado': 'Conteste con un valor entre 1 y 99 según su grado de acuerdo con cada '
                      'frase. 1 es total desacuerdo y 99 total acuerdo.',
         'items': ['Hago bien mis trabajos profesionales.',
                   'Hago fácilmente amigos.',
                   'Tengo miedo de algunas cosas.',
                   'Soy muy criticado/a en casa.',
                   'Me cuido físicamente.',
                   'Mis superiores me consideran un buen trabajador/a.',
                   'Soy una persona amigable.',
                   'Muchas cosas me ponen nervioso/a.',
                   'Me siento feliz en casa.',
                   'Me buscan para realizar actividades deportivas.',
                   'Trabajo mucho en mi profesión.',
                   'Es dificil para mi hacer amigos/as.',
                   'Me asusto con facilidad',
                   'Mi familia está decepcionada de mí.',
                   'Me considero elegante.',
                   'Mis superiores me estiman.',
                   'Soy una persona alegre.',
                   'Cuando alguien con autoridad me dice algo me pongo muy nervioso/a.',
                   'Mi famila me ayudaría en cualquier tipo de problemas.',
                   'Me gusta como soy físicamente.',
                   'Soy un buen trabajador/a.',
                   'Me cuesta hablar con desconocidos.',
                   'Me pongo nervioso/a cuando me pregunta un superior.',
                   'Mis padres me dan confianza.',
                   'Soy bueno/a haciendo deporte.',
                   'Mis superiores me consideran inteligente y trabajador.',
                   'Tengo muchos amigos/as.',
                   'Me siento nervioso/a.',
                   'Me siento querido/a por mis padres.',
                   'Soy una persona atractiva.']},
 'stai_e': {'rotulo': 'Ansiedad: cómo se siente AHORA (STAI-E)',
            'tipo': 'escala',
            'escala': 'stai',
            'enunciado': 'Señale lo que indique mejor cómo se siente usted AHORA MISMO, en '
                         'este momento.',
            'items': ['Me siento calmado',
                      'Me siento seguro',
                      'Estoy Tenso',
                      'Estoy contrariado',
                      'Me siento cómodo (estoy a gusto)',
                      'Me siento alterado',
                      'Estoy preocupado ahora por posibles desgracias futuras',
                      'Me siento descansado',
                      'Me siento angustiado',
                      'Me siento confortable',
                      'Tengo confianza en mi mismo',
                      'Me siento nervioso',
                      'Estoy desasosegado',
                      'Me siento muy “atado” (como oprimido)',
                      'Estoy relajado',
                      'Me siento satisfecho',
                      'Estoy preocupado',
                      'Me siento aturdido y sobreexcitado',
                      'Me siento alegre',
                      'En este momento, me siento bien']},
 'stai_r': {'rotulo': 'Ansiedad: cómo se siente EN GENERAL (STAI-R)',
            'tipo': 'escala',
            'escala': 'stai',
            'enunciado': 'Señale lo que indique mejor cómo se siente usted EN GENERAL, en la '
                         'mayoría de las ocasiones.',
            'items': ['Me siento bien',
                      'Me canso rápidamente',
                      'Siento ganas de llorar',
                      'Me gustaría ser tan feliz como otros',
                      'Pierdo oportunidades por no decidirme pronto',
                      'Me siento descansado',
                      'Soy una persona tranquila, serena y sosegada',
                      'Veo que las dificultades se amontonan y no puedo con ellas',
                      'Me preocupo demasiado por cosas sin importancia',
                      'Soy feliz',
                      'Suelo tomar las cosas demasiado seriamente',
                      'Me falta confianza en mí mismo',
                      'Me siento seguro',
                      'No suelo afrontar las crisis o dificultades',
                      'Me siento triste (melancólico)',
                      'Estoy satisfecho',
                      'Me rondan y molestan pensamientos sin importancia',
                      'Me afectan tanto los desengaños, que no puedo olvidarlos',
                      'Soy una persona estable',
                      'Cuando pienso sobre asuntos actuales, me pongo tenso y agitado']},
 'hipno': {'rotulo': 'Sugestionabilidad',
           'tipo': 'escala',
           'escala': 'frec5',
           'enunciado': 'Valore la frecuencia con que se producen estas situaciones en su vida '
                        'cotidiana.',
           'items': ['La opinión de los demás cuenta mucho para mí.',
                     'Puedo imaginar cosas de forma clara y nítida.',
                     'Me dejo llevar por los demás.',
                     'Es fácil para mí contagiarme del estado de ánimo de los otros.',
                     'Soy una persona sugestionable.',
                     'Tengo ideas o pensamientos supersticiosos.',
                     'Me suelen afectar las películas de terror.',
                     'Cuando me concentro en algo, puedo quedarme absorto/a.',
                     'Soy una persona impresionable.',
                     'Cuando me concentro en mis pensamientos, pierdo fácilmente la noción del '
                     'tiempo.',
                     'Cuando escucho la música que me gusta, me dejo llevar por ella hasta el '
                     'punto de que me olvido de lo demás.',
                     'El sonido de una voz puede ser tan fascinante para mi que puedo '
                     'continuar escuchándola y olvidarme de lo que me rodea.',
                     'Tengo facilidad para concentrarme en la tarea que esté haciendo',
                     'Mientras veo una película, un programa de TV, o una obra de teatro, '
                     'puedo llegar a estar tan implicado/a que me olvido de mi mismo y de mi '
                     'entorno, y experimento la trama como si fuera real o yo formara parte de '
                     'ella.',
                     'Puedo recordar ciertas experiencias pasadas de mi vida con tal claridad '
                     'y realismo, que es como si las estuviera viviendo otra vez.',
                     'Fantaseo a cerca de las cosas que me ocurren o que me gustaría que me '
                     'pasaran.',
                     'Sueño despierto/a',
                     'Las películas emotivas me hacen llorar fácilmente.',
                     'Cambio de opinión con facilidad',
                     'Tiendo a creer lo que me dicen los demás',
                     'Hay personas que me fascinan al primer golpe de vista.',
                     'Dejo que determinadas personas influyan en mi más de lo que considero '
                     'conveniente.']},
 'apego': {'rotulo': 'Modelos de apego',
           'tipo': 'lista',
           'enunciado': 'Marque solo aquellas afirmaciones que considere correctas en su caso.',
           'items': ['A menudo me inquieta la posibilidad de que mi pareja deje de amarme.',
                     'Me resulta fácil demostrar cariño a mi pareja.',
                     'Temo que si alguien llega a conocerme a fondo, no le guste lo que '
                     'descubra.',
                     'Me recupero rápidamente cuando una relación termina. Me resulta extraño '
                     'la facilidad con que puedo quitarme a alguien de la cabeza.',
                     'Cuando no tengo pareja, me siento angustiado/a e incompleto/a',
                     'Me cuesta apoyar emocionalmente a mi pareja cuando atraviesa un mal '
                     'momento.',
                     'Cuando mi pareja no está a mi lado, temo que se interese por otra '
                     'persona.',
                     'Me siento cómodo/a con la idea de depender de mi pareja sentimental.',
                     'Para mí, la independencia es más importante que las relaciones.',
                     'Prefiero no compartir mis sentimientos más íntimos con mi pareja.',
                     'Temo que mi pareja no me corresponda, si le demuestro lo que siento por '
                     'ella.',
                     'Por lo general, mis relaciones me satisfacen.',
                     'No siento la necesidad de demostrar mis sentimientos en el contexto de '
                     'las relaciones afectivas.',
                     'Pienso mucho en mis relaciones.',
                     'Me cuesta depender de mis parejas sentimentales.',
                     'Tiendo a vincularme con rapidez a mi pareja sentimental.',
                     'Me resulta difícil expresarle a mi pareja sentimientos y deseos.',
                     'A veces me enfado o me impacineto con mi pareja sin saber por qué.',
                     'Estoy muy pendiente de los estados de ánimo de mi pareja.',
                     'Creo que la mayoria de las personas son básicamente honradas y de fiar.',
                     'Prefiero el sexo ocasional con alguien que acabo de conocer a intimar '
                     'con un compañero fijo.',
                     'No me incomoda compartir mis sentimientos y pensamientos íntimos con mi '
                     'pareja.',
                     'Temo que mi pareja me abandone si conoce a otra persona.',
                     'Me pone nervioso/a que mi pareja se acerque demasiado a mí.',
                     'En caso de conflicto, tiendo a hacer o decir cosas por impulso de las '
                     'que más tarde me arrepiento.',
                     'Por lo general, las discusiones con mi pareja no hacen que me cuestione '
                     'la relación.',
                     'Mi pareja a menudo desea que me muestre más cariñoso/a de lo que a mi me '
                     'gustaria.',
                     'Me preocupa no ser lo bastante atractivo/a.',
                     'A veces las personas se cansan de mí porque tiendo a provocar pequeños '
                     'dramas en mis relaciones.',
                     'Echo de menos a mi pareja cuando estamos separados, pero cuando vuelvo a '
                     'verla siento la necesidad escapar.',
                     'Cuando disiento de alguien, no me cuesta expresar mi opinión.',
                     'Odio tener la sensación de que otras personas dependen de mí.',
                     'Si me doy cuenta de que alguien que me interesa se fija en otras '
                     'personas, no dejo que la situación me perturbe. Tal vez sienta una '
                     'punzada de celos, pero la situación es pasajera.',
                     'Si me doy cuenta que alguien que me interesa se fija en otras personas, '
                     'me siento aliviado/a. Significa que no pretende entablar un relación en '
                     'exclusividad.',
                     'Si me doy cuenta de que alguien que me interesa se fija en otras '
                     'personas, me deprimo.',
                     'Si la persona con la que salgo empieza a comportarse de manera fría y '
                     'distante, me pregunto que le pasa, pero comprendo que su actitud '
                     'seguramente no tiene nada que ver conmigo.',
                     'Si la persona con la que salgo empieza a comportarse de manera fría y '
                     'distante, lo más probable es que su actitud no me afecte. Tal vez '
                     'incluso me sienta aliviado/a.',
                     'Si la persona con la que salgo empieza a comportarse de manera fría y '
                     'distante, pienso que he hecho algo mal.',
                     'Si mi pareja quisiera romper conmigo, haría lo posible para demostrarle '
                     'lo que se pierde (un poco de celos no hace daño a nadie).',
                     'Si alguien con quien llevo saliendo varios meses quisiera dejar de '
                     'verme, me sentiría herido/a al principio, pero lo superaría.',
                     'A veces cuando consigo lo que quiero de una persona, ya no estoy '
                     'seguro/a de lo que quiero.',
                     'No me importaría seguir en contacto con mi ex (en términos extrictamente '
                     'platónicos). \n'
                     'Al fin y al cabo tenemos mucho en común.']},
 'aron': {'rotulo': 'Alta sensibilidad (Aron)',
          'tipo': 'lista',
          'enunciado': 'Marque las afirmaciones con las que se sienta identificado/a. Si tiene '
                       'dudas, no la marque.',
          'items': ['¿Se siente abrumado con facilidad cuando está en un entorno con muchos '
                    'estímulos?',
                    '¿Suele percibir las sutilezas de su entorno?',
                    '¿Le afectan los estados de ánimo de otras personas?',
                    '¿Tiende a ser más sensible al dolor?',
                    '¿Necesita retirarse durante unas horas a su cama o a una habitación '
                    'oscura cuando ha estado en un lugar estresante?',
                    '¿Es particularmente sensible a los efectos de la cafeína?',
                    '¿Le abruman cosas como luces brillantes, olores fuertes, telas ásperas, '
                    'el sonido del tráfico, etc?',
                    '¿Siente que tiene una vida interior rica y compleja?',
                    '¿Le incomodan los ruidos fuertes?',
                    '¿Le conmueven las artes, la música, etc?',
                    '¿Necesita soledad cuando hay muchos estímulos a su alrededor?',
                    '¿Es usted tenaz en lo que se propone?',
                    '¿Se asusta fácilmente?',
                    '¿Se abruma cuando tiene mucho que hacer en poco tiempo?',
                    '¿Percibe de inmediato cuando a alguien de su alrededor le ocurre algo?',
                    '¿Le molesta cuando la gente le pide que haga varias cosas a la vez?',
                    '¿Se esfuerza mucho por evitar cometer errores u olvidar cosas?',
                    '¿Evita ver películas y programas de televisión violentos?',
                    '¿Se siente saturado cuando pasan muchas cosas a su alrededor?',
                    'Cuando tiene hambre ¿cambia su estado de ánimo?',
                    '¿Le alteran los cambios más pequeños en su día a día?',
                    '¿Disfruta de los aromas delicados, de sabores y sonidos suaves?',
                    '¿Es incómodo para usted tener muchos objetos o estímulos a su alrededor?',
                    '¿Le da mayor prioridad a organizar su vida para evitar situaciones '
                    'molestas o abrumadoras?',
                    '¿Le molesta que le observen cuando tiene que hacer algo?',
                    '¿Se siente bloqueado cuando debe competir?',
                    'Cuando era niño, ¿sus padres y profesores solían decir de usted que era '
                    'tímido o demasiado sensible?']},
 'bdi': {'rotulo': 'Estado de ánimo (BDI-II)',
         'tipo': 'grupos',
         'enunciado': 'En cada grupo, elija la frase que mejor describa cómo se ha sentido las '
                      'últimas dos semanas, incluyendo hoy. Si varias le parecen igual de '
                      'apropiadas, marque la del número más alto.',
         'items': [{'titulo': 'Tristeza',
                    'opciones': ['0 · No me siento triste.',
                                 '1 · Me siento triste gran parte del tiempo',
                                 '2 · Me siento triste todo el tiempo.',
                                 '3 · Me siento tan triste o soy tan infeliz que no puedo '
                                 'soportarlo.']},
                   {'titulo': 'Pesimismo',
                    'opciones': ['0 · No estoy desalentado respecto del mi futuro.',
                                 '1 · Me siento más desalentado respecto de mi futuro que lo '
                                 'que solía estarlo.',
                                 '2 · No espero que las cosas funcionen para mí.',
                                 '3 · Siento que no hay esperanza para mi futuro y que sólo '
                                 'puede empeorar.']},
                   {'titulo': 'Fracaso',
                    'opciones': ['0 · No me siento como un fracasado.',
                                 '1 · He fracasado más de lo que hubiera debido.',
                                 '2 · Cuando miro hacia atrás, veo muchos fracasos.',
                                 '3 · Siento que como persona soy un fracaso total.']},
                   {'titulo': 'Pérdida de Placer',
                    'opciones': ['0 · Obtengo tanto placer como siempre por las cosas de las '
                                 'que disfruto.',
                                 '1 · No disfruto tanto de las cosas como solía hacerlo.',
                                 '2 · Obtengo muy poco placer de las cosas que solía '
                                 'disfrutar.',
                                 '3 · No puedo obtener ningún placer de las cosas de las que '
                                 'solía disfrutar.']},
                   {'titulo': 'Sentimientos de Culpa',
                    'opciones': ['0 · No me siento particularmente culpable.',
                                 '1 · Me siento culpable respecto de varias cosas que he hecho '
                                 'o que debería haber hecho.',
                                 '2 · Me siento bastante culpable la mayor parte del tiempo.',
                                 '3 · Me siento culpable todo el tiempo.']},
                   {'titulo': 'Sentimientos de Castigo',
                    'opciones': ['0 · No siento que este siendo castigado',
                                 '1 · Siento que tal vez pueda ser castigado.',
                                 '2 · Espero ser castigado.',
                                 '3 · Siento que estoy siendo castigado.']},
                   {'titulo': 'Disconformidad con uno mismo.',
                    'opciones': ['0 · Siento acerca de mi lo mismo que siempre.',
                                 '1 · He perdido la confianza en mí mismo.',
                                 '2 · Estoy decepcionado conmigo mismo.',
                                 '3 · No me gusto a mí mismo.']},
                   {'titulo': 'Autocrítica',
                    'opciones': ['0 · No me critico ni me culpo más de lo habitual',
                                 '1 · Estoy más crítico conmigo mismo de lo que solía estarlo',
                                 '2 · Me critico a mí mismo por todos mis errores',
                                 '3 · Me culpo a mí mismo por todo lo malo que sucede.']},
                   {'titulo': 'Pensamientos o Deseos Suicidas',
                    'opciones': ['0 · No tengo ningún pensamiento de matarme.',
                                 '1 · He tenido pensamientos de matarme, pero no lo haría',
                                 '2 · Querría matarme',
                                 '3 · Me mataría si tuviera la oportunidad de hacerlo.']},
                   {'titulo': 'Llanto',
                    'opciones': ['0 · No lloro más de lo que solía hacerlo.',
                                 '1 · Lloro más de lo que solía hacerlo',
                                 '2 · Lloro por cualquier pequeñez.',
                                 '3 · Siento ganas de llorar, pero no puedo.']},
                   {'titulo': 'Agitación',
                    'opciones': ['0 · No estoy más inquieto o tenso que lo habitual.',
                                 '1 · Me siento más inquieto o tenso que lo habitual.',
                                 '2 · Estoy tan inquieto o agitado que me es difícil quedarme '
                                 'quieto',
                                 '3 · Estoy tan inquieto o agitado que tengo que estar siempre '
                                 'en movimiento o haciendo algo.']},
                   {'titulo': 'Pérdida de Interés',
                    'opciones': ['0 · No he perdido el interés en otras actividades o '
                                 'personas.',
                                 '1 · Estoy menos interesado que antes en otras personas o '
                                 'cosas.',
                                 '2 · He perdido casi todo el interés en otras personas o '
                                 'cosas.',
                                 '3 · Me es difícil interesarme por algo.']},
                   {'titulo': 'Indecisión',
                    'opciones': ['0 · Tomo mis propias decisiones tan bien como siempre.',
                                 '1 · Me resulta más difícil que de costumbre tomar decisiones',
                                 '2 · Encuentro mucha más dificultad que antes para tomar '
                                 'decisiones.',
                                 '3 · Tengo problemas para tomar cualquier decisión.']},
                   {'titulo': 'Desvalorización',
                    'opciones': ['0 · No siento que yo no sea valioso',
                                 '1 · No me considero a mí mismo tan valioso y útil como solía '
                                 'considerarme',
                                 '2 · Me siento menos valioso cuando me comparo con otros.',
                                 '3 · Siento que no valgo nada.']},
                   {'titulo': 'Pérdida de Energía',
                    'opciones': ['0 · Tengo tanta energía como siempre.',
                                 '1 · Tengo menos energía que la que solía tener.',
                                 '2 · No tengo suficiente energía para hacer demasiado',
                                 '3 · No tengo energía suficiente para hacer nada.']},
                   {'titulo': 'Cambios en los Hábitos de Sueño',
                    'opciones': ['0 · No he experimentado ningún cambio en mis hábitos de '
                                 'sueño.',
                                 '1a · Duermo un poco más que lo habitual.',
                                 '1b · Duermo un poco menos que lo habitual.',
                                 '2a · Duermo mucho más que lo habitual.',
                                 '2b · Duermo mucho menos que lo habitual',
                                 '3a · Duermo la mayor parte del día',
                                 '3b · Me despierto 1-2 horas más temprano y no puedo volver a '
                                 'dormirme']},
                   {'titulo': 'Irritabilidad',
                    'opciones': ['0 · No estoy tan irritable que lo habitual.',
                                 '1 · Estoy más irritable que lo habitual.',
                                 '2 · Estoy mucho más irritable que lo habitual.',
                                 '3 · Estoy irritable todo el tiempo.']},
                   {'titulo': 'Cambios en el Apetito',
                    'opciones': ['0 · No he experimentado ningún cambio en mi apetito.',
                                 '1a · Mi apetito es un poco menor que lo habitual.',
                                 '1b · Mi apetito es un poco mayor que lo habitual.',
                                 '2a · Mi apetito es mucho menor que antes.',
                                 '2b · Mi apetito es mucho mayor que lo habitual',
                                 '3a · No tengo apetito en absoluto.',
                                 '3b · Quiero comer todo el día.']},
                   {'titulo': 'Dificultad de Concentración',
                    'opciones': ['0 · Puedo concentrarme tan bien como siempre.',
                                 '1 · No puedo concentrarme tan bien como habitualmente',
                                 '2 · Me es difícil mantener la mente en algo por mucho '
                                 'tiempo.',
                                 '3 · Encuentro que no puedo concentrarme en nada.']},
                   {'titulo': 'Cansancio o Fatiga',
                    'opciones': ['0 · No estoy más cansado o fatigado que lo habitual.',
                                 '1 · Me fatigo o me canso más fácilmente que lo habitual.',
                                 '2 · Estoy demasiado fatigado o cansado para hacer muchas de '
                                 'las cosas que solía hacer.',
                                 '3 · Estoy demasiado fatigado o cansado para hacer la mayoría '
                                 'de las cosas que solía']},
                   {'titulo': 'Pérdida de Interés en el Sexo',
                    'opciones': ['0 · No he notado ningún cambio reciente en mi interés por el '
                                 'sexo.',
                                 '1 · Estoy menos interesado en el sexo de lo que solía '
                                 'estarlo.',
                                 '2 · Estoy mucho menos interesado en el sexo.',
                                 '3 · He perdido completamente el interés en el sexo.']}]},
 'creencias': {'rotulo': 'Creencias negativas',
               'tipo': 'lista_cat',
               'enunciado': 'Marque aquellas creencias negativas con las que cree que se '
                            'identifica.',
               'items': [{'categoria': 'Auto Concepto', 'texto': 'No estoy bien como soy'},
                         {'categoria': 'Auto Concepto', 'texto': 'No merezco ser amado'},
                         {'categoria': 'Auto Concepto', 'texto': 'Soy una mala persona'},
                         {'categoria': 'Auto Concepto',
                          'texto': 'No valgo nada, no sirvo, soy inútil'},
                         {'categoria': 'Auto Concepto', 'texto': 'Soy una vergüenza'},
                         {'categoria': 'Auto Concepto',
                          'texto': 'No soy querible, no me pueden querer'},
                         {'categoria': 'Auto Concepto', 'texto': 'Merezco solo cosas malas'},
                         {'categoria': 'Auto Concepto', 'texto': 'Estoy dañado para siempre'},
                         {'categoria': 'Auto Concepto', 'texto': 'Soy una desilusión'},
                         {'categoria': 'Auto Concepto', 'texto': 'Soy tonto'},
                         {'categoria': 'Auto Concepto',
                          'texto': 'Soy insignificante (poco importante)'},
                         {'categoria': 'Auto Concepto', 'texto': 'Merezco morir'},
                         {'categoria': 'Auto Concepto',
                          'texto': 'Soy feo. Mi cuerpo es detestable'},
                         {'categoria': 'Auto Concepto', 'texto': 'Soy inseguro, débil'},
                         {'categoria': 'Auto Concepto', 'texto': 'Soy torpe, poco capaz'},
                         {'categoria': 'Responsabilidad',
                          'texto': 'Tendría que haber hecho algo'},
                         {'categoria': 'Responsabilidad',
                          'texto': 'Hice algo malo, por eso soy malo'},
                         {'categoria': 'Responsabilidad',
                          'texto': 'Debería haber sabido hacerlo mejor'},
                         {'categoria': 'Responsabilidad',
                          'texto': 'Fue mi culpa. No merezco perdón'},
                         {'categoria': 'Peligro', 'texto': 'No se puede confiar en mí'},
                         {'categoria': 'Peligro', 'texto': 'No confío en mí mismo'},
                         {'categoria': 'Peligro', 'texto': 'No puedo confiar en mis juicios'},
                         {'categoria': 'Peligro', 'texto': 'No puedo confiar en nadie'},
                         {'categoria': 'Peligro', 'texto': 'No puedo cuidarme, protegerme'},
                         {'categoria': 'Peligro', 'texto': 'Estoy todavía en peligro'},
                         {'categoria': 'Peligro',
                          'texto': 'No puedo mostrar emociones con seguridad'},
                         {'categoria': 'Peligro', 'texto': 'No puedo pedir lo que quiero'},
                         {'categoria': 'Peligro', 'texto': 'No puedo contarlo'},
                         {'categoria': 'Falta de control', 'texto': 'No puedo tener control'},
                         {'categoria': 'Falta de control', 'texto': 'Soy débil, temeroso'},
                         {'categoria': 'Falta de control',
                          'texto': 'Soy un fracaso (voy a fracasar)'},
                         {'categoria': 'Falta de control',
                          'texto': 'No logro tener lo que quiero'},
                         {'categoria': 'Falta de control', 'texto': 'No puedo tener éxito'},
                         {'categoria': 'Falta de control', 'texto': 'Soy pesimista, negativo'},
                         {'categoria': 'Falta de control',
                          'texto': 'No tengo fuerzas, no tengo opciones'},
                         {'categoria': 'Falta de control',
                          'texto': 'No me puedo proteger, soy vulnerable'}]},
 'iatp': {'rotulo': 'Adjetivos que le definen (IA-TP)',
          'tipo': 'lista',
          'enunciado': 'Marque los adjetivos que cree que le definen mejor.',
          'items': ['Pasivo',
                    'Agitado',
                    'Consentido',
                    'Activo',
                    'Arrogante',
                    'Agresivo',
                    'Cuidadoso',
                    'Confuso',
                    'Distante',
                    'Triste',
                    'Auxiliador',
                    'Complaciente',
                    'Creído',
                    'Autoritario',
                    'Disciplinado',
                    'Exasperante',
                    'Ansioso',
                    'Deprimido',
                    'Frío',
                    'Desapercibido',
                    'Cándido',
                    'Audaz',
                    'Confiado',
                    'Grosero',
                    'Eficiente',
                    'Variable',
                    'Caótico',
                    'Extravagante',
                    'Inexpresivo',
                    'Discreto',
                    'Cariñoso',
                    'Animado',
                    'Egoísta',
                    'Brutal',
                    'Formal',
                    'Exaltado',
                    'Sensible',
                    'Impersonal',
                    'Discutidor',
                    'Comprensivo',
                    'Dramatizador',
                    'Fanfarrón',
                    'Competitivo',
                    'Honrado',
                    'Gruñón',
                    'Abatido',
                    'Indiferente',
                    'Excluido',
                    'Estricto',
                    'Disgustado',
                    'Apático',
                    'Ignorado',
                    'Nervioso',
                    'Feliz',
                    'Egocéntrico',
                    'Dominante',
                    'Limpio',
                    'Irritable',
                    'Desagradable',
                    'Pensativo',
                    'Insociable',
                    'Inquieto',
                    'Inseguro',
                    'Reservado',
                    'Miedoso',
                    'Receloso',
                    'Impulsivo',
                    'Importante',
                    'Combativo',
                    'Laborioso',
                    'Malhumorado',
                    'Frustrante',
                    'Rígido',
                    'Aprehensivo',
                    'Incómodo',
                    'Solitario',
                    'Suspicaz',
                    'Voluble',
                    'Hablador',
                    'Inmodesto',
                    'Fuerte',
                    'Ordenado',
                    'Inconstante',
                    'Vengativo',
                    'Atrevido',
                    'Preocupado',
                    'Dócil',
                    'Infantil',
                    'Optimista',
                    'Violento',
                    'Molesto',
                    'Solo',
                    'Vacilante',
                    'Murmurador',
                    'Organizado',
                    'Mandón',
                    'Orgulloso',
                    'Impaciente',
                    'Inocente',
                    'Tímido',
                    'Educado',
                    'Apagado',
                    'Vago',
                    'Rechazado',
                    'Grupal',
                    'Sociable',
                    'Vanidoso',
                    'Intimidante',
                    'Trabajador',
                    'Susceptible',
                    'Hostil',
                    'Obediente',
                    'Conformista',
                    'Tenso',
                    'Perfeccionista',
                    'Valiente',
                    'Satisfecho',
                    'Vital',
                    'Sumiso',
                    'Temeroso',
                    'Ético',
                    'Temperamental',
                    'Preciso',
                    'Abnegado',
                    'Militante',
                    'Gregario',
                    'Dependiente',
                    'Tradicional',
                    'Aventurero',
                    'Antipático',
                    'Desprendido',
                    'Teatral',
                    'Presumido',
                    'Tozudo',
                    'Serio',
                    'Pesimista',
                    'Obstinado',
                    'Quisquilloso',
                    'Respetuoso',
                    'Poderoso',
                    'Vistuoso',
                    'Provocador',
                    'Encantador',
                    'Desinteresado',
                    'Seductor',
                    'Insípido']}}
