name: End-to-End Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  e2e-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]
        browser: [chromium, firefox, webkit]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Install Playwright browsers
      run: npx playwright install --with-deps ${{ matrix.browser }}

    - name: Build the application
      run: npm run build

    - name: Start the application
      run: |
        npm start &
        # Wait for the server to be ready
        sleep 30
        curl -f http://localhost:8080 || exit 1

    - name: Run Playwright tests
      run: npm run test:e2e -- --project=${{ matrix.browser }} --reporter=list

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: playwright-results-${{ matrix.browser }}
        path: playwright-report/

  mobile-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Install Playwright browsers
      run: npx playwright install --with-deps

    - name: Build the application
      run: npm run build

    - name: Start the application
      run: |
        npm start &
        sleep 30
        curl -f http://localhost:8080 || exit 1

    - name: Run mobile tests
      run: npm run test:e2e:mobile

    - name: Upload mobile test results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: playwright-mobile-results
        path: playwright-report/

  accessibility-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Install Playwright browsers
      run: npx playwright install --with-deps

    - name: Build the application
      run: npm run build

    - name: Start the application
      run: |
        npm start &
        sleep 30
        curl -f http://localhost:8080 || exit 1

    - name: Run accessibility tests
      run: npx playwright test tests/e2e/accessibility.spec.ts

    - name: Upload accessibility test results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: playwright-accessibility-results
        path: playwright-report/

  critical-flows:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Install Playwright browsers
      run: npx playwright install --with-deps chromium

    - name: Build the application
      run: npm run build

    - name: Start the application
      run: |
        npm start &
        sleep 30
        curl -f http://localhost:8080 || exit 1

    - name: Run critical flow tests only
      run: |
        npx playwright test tests/e2e/contact-form.spec.ts
        npx playwright test tests/e2e/mobile-menu.spec.ts
        npx playwright test tests/e2e/cookie-banner.spec.ts

    - name: Upload critical flow results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: playwright-critical-results
        path: playwright-report/