name: Scrape Doctoralia Calendar

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"

jobs:
  scrape:
    runs-on: ubuntu-latest
    
    # 👇 ESTA SECCIÓN ES CLAVE 👇
    # Le da permiso a ESTA ACCIÓN específica para escribir en tu repositorio.
    # No es una credencial, es una regla de seguridad para este flujo de trabajo.
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0
          fetch-tags: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Set up Google Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium webdriver-manager

      - name: Run scraper
        run: python scraper.py
      
      - name: Sync with remote before committing
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git checkout main
          git pull --rebase origin main

          
      # Usamos la Action especializada que se encargará de todo automáticamente
      - name: Commit and push if changed
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: "chore: Actualizar horarios de Doctoralia"
          file_pattern: public/api/horarios.json
          branch: main
          pull: true  # <-- Esto permite a la acción hacer pull antes del push
